services:
  car-mgt-service:
    build: .
    volumes:
      - ./car-mgt-service:/car-mgt-service
      - ./logs:/car-mgt-service/var/log
    depends_on:
      - redis
      - mysql
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=mysql://car_owner:pass1234@mysql:3306/car_mgt
    ports: 
      - "8000:8000"
    networks:
      - car_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - car_network

  mysql:
    image: mysql:latest
    container_name: mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_mgt
      MYSQL_USER: car_owner
      MYSQL_PASSWORD: pass1234
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - car_network

volumes:
  redis-data:
  mysql-data:

networks:
  car_network: