services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./car-mgt-service:/var/www/html
    networks:
      - car_network
    user: www-data

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car_mgt
      MYSQL_USER: car_owner
      MYSQL_PASSWORD: pass1234
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - car_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - car_network

networks:
  car_network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: