monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - app_error
        - app_info

when@dev:
    monolog:
        handlers:
            error_log:
                type: stream
                path: "%kernel.logs_dir%/error-%kernel.environment%.log"
                level: error
                channels: ["app_error"]

            info_log:
                type: stream
                path: "%kernel.logs_dir%/log-%kernel.environment%.log"
                level: info
                channels: ["app_info"]

when@test:
    monolog:
        handlers:
            error_log:
                type: stream
                path: "%kernel.logs_dir%/error-%kernel.environment%.log"
                level: error
                channels: ["app_error"]

            info_log:
                type: stream
                path: "%kernel.logs_dir%/log-%kernel.environment%.log"
                level: info
                channels: ["app_info"]

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
                formatter: monolog.formatter.json
